apiVersion: v1
kind: Service
metadata:
  name: super-compara-frontend
  namespace: super-compara
  labels:
    app: super-compara-frontend
spec:
  type: ClusterIP
  selector:
    app: super-compara-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
