apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: super-compara-ingress
  namespace: super-compara
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: super-compara-backend
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: super-compara-frontend
            port:
              number: 80
